# Generated by Django 4.1.4 on 2022-12-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('branch', models.CharField(choices=[('CSE', 'css'), ('ISE', 'ISE'), ('ECE', 'ECE'), ('AIML', 'AIML'), ('EEE', 'EEE')], default='CSE', max_length=5)),
                ('catagory', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('stipend', models.IntegerField(default='30000')),
                ('role', models.CharField(max_length=100)),
                ('jobloction', models.CharField(default='BAngalore', max_length=100)),
                ('dateofdrive', models.DateField(default=2000)),
                ('lastdate', models.DateField(default=2001)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sponsor', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('eligible_branch', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('fee', models.IntegerField()),
            ],
        ),
    ]
