# Generated by Django 4.1.4 on 2022-12-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_companies',
            name='aggregate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='all_companies',
            name='branch',
            field=models.CharField(choices=[('CSE', 'css'), ('ISE', 'ISE'), ('ECE', 'ECE'), ('AIML', 'AIML'), ('EEE', 'EEE')], default='CS', max_length=5),
        ),
    ]
