# Generated by Django 4.1.4 on 2023-06-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0002_delete_training_alter_all_companies_aggregate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='placed',
        ),
    ]
