# Generated by Django 4.1.4 on 2022-12-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0003_alter_all_companies_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_companies',
            name='branch',
            field=models.CharField(choices=[('cse', 'CSE'), ('ise', 'ISE'), ('aiml', 'AIML'), ('ece', 'ECE'), ('eee', 'EEE'), ('mech', 'MECHANICAL'), ('civil', 'CIVIL')], default='cse', max_length=5),
        ),
        migrations.AlterField(
            model_name='all_companies',
            name='catagory',
            field=models.CharField(choices=[('it', 'IT'), ('core', 'CORE')], default='it', max_length=50),
        ),
    ]
