# Generated by Django 4.1.4 on 2022-12-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0005_alter_all_companies_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_companies',
            name='branch',
        ),
        migrations.AddField(
            model_name='all_companies',
            name='branch1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='all_companies',
            name='branch2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='all_companies',
            name='branch3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='all_companies',
            name='branch4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='all_companies',
            name='branch5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='all_companies',
            name='branch6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='all_companies',
            name='branch7',
            field=models.BooleanField(default=False),
        ),
    ]
