# Generated by Django 4.1.4 on 2023-06-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0006_alter_studentdetails_usn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='USN',
            field=models.CharField(max_length=10),
        ),
    ]
