# Generated by Django 4.1.4 on 2022-12-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0006_remove_all_companies_branch_all_companies_branch1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='mode',
            field=models.CharField(choices=[('online', 'ONLINE'), ('offline', 'OFFLINE')], default='offline', max_length=10),
        ),
    ]
