# Generated by Django 4.1.4 on 2022-12-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0007_alter_training_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='name',
            new_name='course_name',
        ),
    ]
