# Generated by Django 4.1.4 on 2022-12-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0008_rename_name_training_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='mode',
            field=models.CharField(choices=[('online', 'ONLINE'), ('offline', 'OFFLINE')], default='offline', max_length=10, null=True),
        ),
    ]
