# Generated by Django 4.1.4 on 2022-12-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0009_alter_training_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='mode',
            field=models.CharField(choices=[('online', 'ONLINE'), ('offline', 'OFFLINE')], default='offline', max_length=10),
        ),
    ]
