# Generated by Django 4.1.4 on 2022-12-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0012_alter_training_location_alter_training_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
