# Generated by Django 4.1.4 on 2022-12-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0013_alter_training_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
