# Generated by Django 4.1.4 on 2022-12-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0015_alter_all_companies_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_companies',
            name='jobloction',
        ),
        migrations.AddField(
            model_name='all_companies',
            name='joblocation',
            field=models.CharField(default='BAngalore', max_length=100),
        ),
    ]
