# Generated by Django 4.1.4 on 2022-12-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0016_remove_all_companies_jobloction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_companies',
            name='catagory',
            field=models.CharField(choices=[('it', 'IT'), ('core', 'CORE')], default='it', max_length=50),
        ),
    ]
