# Generated by Django 4.1.4 on 2022-12-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0018_alter_all_companies_catagory_alter_training_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_companies',
            name='catagory',
            field=models.CharField(choices=[('IT', 'it'), ('CORE', 'core')], default='IT', max_length=50),
        ),
    ]
