# Generated by Django 4.1.4 on 2022-12-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0019_alter_all_companies_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='domain',
            field=models.CharField(choices=[('ONLINE', 'online'), ('OFFLINE', 'offline')], max_length=50),
        ),
    ]
