# Generated by Django 4.1.4 on 2022-12-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0020_alter_training_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_companies',
            name='catagory',
            field=models.CharField(choices=[('it', 'IT'), ('core', 'CORE')], default='IT', max_length=50),
        ),
    ]
