# Generated by Django 4.1.4 on 2022-12-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0022_alter_training_domain_alter_training_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_companies',
            name='catagory',
            field=models.CharField(choices=[('IT', 'IT'), ('CORE', 'CORE')], default='IT', max_length=50),
        ),
        migrations.AlterField(
            model_name='all_companies',
            name='joblocation',
            field=models.CharField(default='Bangalore', max_length=100),
        ),
        migrations.AlterField(
            model_name='training',
            name='domain',
            field=models.CharField(choices=[('IT', 'IT'), ('CORE', 'CORE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='training',
            name='mode',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('ONLINE', 'OFFLINE')], default='offline', max_length=10),
        ),
    ]
