# Generated by Django 4.1.4 on 2023-03-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0025_student_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Models',
            fields=[
                ('Current_Education_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('First_Sem_GPA', models.FloatField(max_length=10)),
                ('Second_Sem_GPA', models.FloatField(max_length=10)),
                ('Third_Sem_GPA', models.FloatField(max_length=10)),
                ('Fourth_Sem_GPA', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Past_Models',
            fields=[
                ('Past_Education_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Tenth_Grade', models.FloatField(max_length=6)),
                ('Twelth_Grade', models.FloatField(max_length=6)),
                ('KCET_Rank', models.IntegerField(max_length=6)),
                ('Tenth_Scheme', models.CharField(choices=[('State', 'State'), ('CBSC', 'CBSC')], default='State', max_length=30)),
                ('Twelth_Scheme', models.CharField(choices=[('State', 'State'), ('CBSC', 'CBSC')], default='State', max_length=30)),
            ],
        ),
    ]
