# Generated by Django 4.1.4 on 2023-05-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0028_alter_all_companies_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_companies',
            name='branch',
            field=models.CharField(max_length=100),
        ),
    ]
