# Generated by Django 4.1.4 on 2023-05-09 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0033_rename_student_id_registration_com_student_usn_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration_Com',
        ),
    ]
