# Generated by Django 4.1.4 on 2023-05-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0035_student_details_student_id_registration_com'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='student_id',
        ),
    ]
