# Generated by Django 4.1.4 on 2023-05-09 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0036_remove_student_details_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration_Com',
        ),
    ]
