# Generated by Django 4.1.4 on 2023-05-17 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0038_registration_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_com',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlacementApp.all_companies'),
        ),
    ]
