# Generated by Django 4.1.4 on 2023-05-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0039_alter_reg_com_company_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration_Com',
        ),
    ]
