# Generated by Django 4.1.4 on 2023-05-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0040_delete_registration_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_com',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
