# Generated by Django 4.1.4 on 2023-05-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementApp', '0041_alter_reg_com_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg_com',
            name='id',
        ),
        migrations.AlterField(
            model_name='reg_com',
            name='company_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
